name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'  # Usando a versão 20.16.0 do Node.js

    - name: Install dependencies
      run: npm install

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run K6 tests
      run: k6 run PerformanceTest/k6.test.js  # Executa o script de teste K6

    - name: Run Cypress tests
      run: npx cypress run  # Executa os testes do Cypress, se aplicável

    - name: Run Jest tests
      run: npm test  # Executa os testes do Jest, se aplicável
