name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: Install dependencies
      run: npm install

    - name: Run K6 tests
      uses: loadimpact/k6-action@v1
      with:
        script: PerformanceTest/k6.test.js

    - name: Run Cypress tests
      run: npx cypress run

    - name: Run Jest tests
      run: npm test
